# Generated by Django 4.0.2 on 2023-09-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_alter_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
